### ISSUE TITLE
SDPA: scaled_dot_product_attention to use this attetino donot need to retain ?

### ISSUE THREAD

**Issue by ganliqiang** [pytorch-labs/ao#14]
when use new sdpa,why does it dont need to be trained,now paras is added ?

**Comment by supriyar** [comment]
cc @drisspg @cpuhrsch

**Comment by drisspg** [comment]
SDPA is a purely functional op so in if you pass in the existing parameters from the trained model you should not have to retrain.

**Comment by HDCharles** [comment]
I'm going to close the issue since its not related to the torchao repository feel free to continue the discussion in the [pytorch forums](https://discuss.pytorch.org/) or in an issue in the [pytorch repo ](https://github.com/pytorch/pytorch/issues/new/choose)
